//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EtHerG.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ScatterPoints {
            get {
                return ((int)(this["ScatterPoints"]));
            }
            set {
                this["ScatterPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Alarm1ModbusAddress {
            get {
                return ((ushort)(this["Alarm1ModbusAddress"]));
            }
            set {
                this["Alarm1ModbusAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort Alarm2ModbusAddress {
            get {
                return ((ushort)(this["Alarm2ModbusAddress"]));
            }
            set {
                this["Alarm2ModbusAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LineDiagPoints {
            get {
                return ((int)(this["LineDiagPoints"]));
            }
            set {
                this["LineDiagPoints"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DiagMaxPointSize {
            get {
                return ((int)(this["DiagMaxPointSize"]));
            }
            set {
                this["DiagMaxPointSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Alarm1Value {
            get {
                return ((int)(this["Alarm1Value"]));
            }
            set {
                this["Alarm1Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Alarm2Value {
            get {
                return ((int)(this["Alarm2Value"]));
            }
            set {
                this["Alarm2Value"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort PlayModbusAddress {
            get {
                return ((ushort)(this["PlayModbusAddress"]));
            }
            set {
                this["PlayModbusAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort FrequencyModbusAddress {
            get {
                return ((ushort)(this["FrequencyModbusAddress"]));
            }
            set {
                this["FrequencyModbusAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float Frequency {
            get {
                return ((float)(this["Frequency"]));
            }
            set {
                this["Frequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort GainXModbusAddress {
            get {
                return ((ushort)(this["GainXModbusAddress"]));
            }
            set {
                this["GainXModbusAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GainX {
            get {
                return ((float)(this["GainX"]));
            }
            set {
                this["GainX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float GainY {
            get {
                return ((float)(this["GainY"]));
            }
            set {
                this["GainY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort GainYModbusAddress {
            get {
                return ((ushort)(this["GainYModbusAddress"]));
            }
            set {
                this["GainYModbusAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float Phase {
            get {
                return ((float)(this["Phase"]));
            }
            set {
                this["Phase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float FilterLP {
            get {
                return ((float)(this["FilterLP"]));
            }
            set {
                this["FilterLP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public float FilterHP {
            get {
                return ((float)(this["FilterHP"]));
            }
            set {
                this["FilterHP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort PhaseModbusAddress {
            get {
                return ((ushort)(this["PhaseModbusAddress"]));
            }
            set {
                this["PhaseModbusAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort FilterLPModbusAddress {
            get {
                return ((ushort)(this["FilterLPModbusAddress"]));
            }
            set {
                this["FilterLPModbusAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort FilterHPModbusAddress {
            get {
                return ((ushort)(this["FilterHPModbusAddress"]));
            }
            set {
                this["FilterHPModbusAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ModbusServerIP {
            get {
                return ((string)(this["ModbusServerIP"]));
            }
            set {
                this["ModbusServerIP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ModbusServerPort {
            get {
                return ((int)(this["ModbusServerPort"]));
            }
            set {
                this["ModbusServerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ComPort {
            get {
                return ((int)(this["ComPort"]));
            }
            set {
                this["ComPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EtherAutoconnect {
            get {
                return ((bool)(this["EtherAutoconnect"]));
            }
            set {
                this["EtherAutoconnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ModbusAutoconnect {
            get {
                return ((bool)(this["ModbusAutoconnect"]));
            }
            set {
                this["ModbusAutoconnect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Autologin {
            get {
                return ((bool)(this["Autologin"]));
            }
            set {
                this["Autologin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1896")]
        public int LineDiagSizeX {
            get {
                return ((int)(this["LineDiagSizeX"]));
            }
            set {
                this["LineDiagSizeX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("315")]
        public int LineDiagSizeY {
            get {
                return ((int)(this["LineDiagSizeY"]));
            }
            set {
                this["LineDiagSizeY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LineDiagPosX {
            get {
                return ((int)(this["LineDiagPosX"]));
            }
            set {
                this["LineDiagPosX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("698")]
        public int LineDiagPosY {
            get {
                return ((int)(this["LineDiagPosY"]));
            }
            set {
                this["LineDiagPosY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("343")]
        public int ScatterDiagPosX {
            get {
                return ((int)(this["ScatterDiagPosX"]));
            }
            set {
                this["ScatterDiagPosX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public int ScatterDiagPosY {
            get {
                return ((int)(this["ScatterDiagPosY"]));
            }
            set {
                this["ScatterDiagPosY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400")]
        public int ScatterDiagSize {
            get {
                return ((int)(this["ScatterDiagSize"]));
            }
            set {
                this["ScatterDiagSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DisableUserInput {
            get {
                return ((bool)(this["DisableUserInput"]));
            }
            set {
                this["DisableUserInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InfluxDBEnabled {
            get {
                return ((bool)(this["InfluxDBEnabled"]));
            }
            set {
                this["InfluxDBEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ModbusLastSentAddressEnabled {
            get {
                return ((bool)(this["ModbusLastSentAddressEnabled"]));
            }
            set {
                this["ModbusLastSentAddressEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort FrequencyModbusLastSendAddress {
            get {
                return ((ushort)(this["FrequencyModbusLastSendAddress"]));
            }
            set {
                this["FrequencyModbusLastSendAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort GainXModbusLastSendAddress {
            get {
                return ((ushort)(this["GainXModbusLastSendAddress"]));
            }
            set {
                this["GainXModbusLastSendAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort GainYModbusLastSendAddress {
            get {
                return ((ushort)(this["GainYModbusLastSendAddress"]));
            }
            set {
                this["GainYModbusLastSendAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort PhaseModbusLastSendAddress {
            get {
                return ((ushort)(this["PhaseModbusLastSendAddress"]));
            }
            set {
                this["PhaseModbusLastSendAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort FilterLPModbusLastSendAddress {
            get {
                return ((ushort)(this["FilterLPModbusLastSendAddress"]));
            }
            set {
                this["FilterLPModbusLastSendAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public ushort FilterHPModbusLastSendAddress {
            get {
                return ((ushort)(this["FilterHPModbusLastSendAddress"]));
            }
            set {
                this["FilterHPModbusLastSendAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfluxDBServer {
            get {
                return ((string)(this["InfluxDBServer"]));
            }
            set {
                this["InfluxDBServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfluxDBToken {
            get {
                return ((string)(this["InfluxDBToken"]));
            }
            set {
                this["InfluxDBToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfluxDBOrgID {
            get {
                return ((string)(this["InfluxDBOrgID"]));
            }
            set {
                this["InfluxDBOrgID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfluxDBBucket {
            get {
                return ((string)(this["InfluxDBBucket"]));
            }
            set {
                this["InfluxDBBucket"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string InfluxDBMachine {
            get {
                return ((string)(this["InfluxDBMachine"]));
            }
            set {
                this["InfluxDBMachine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowX {
            get {
                return ((bool)(this["ShowX"]));
            }
            set {
                this["ShowX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowY {
            get {
                return ((bool)(this["ShowY"]));
            }
            set {
                this["ShowY"] = value;
            }
        }
    }
}
